# -*- coding: utf-8 -*-
"""BCG Task III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Efm9NyMAYINe0Jy0_XBZLsb5yK78B-0
"""

import pandas as pd

df = pd.read_csv('/content/clean_data_after_eda.csv')
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')

df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')

df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')

df.head(3)

price_df = pd.read_csv('/content/price_data.csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

# Group off-peak prices by companies and month
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()

# Get january and december prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

# Calculate the difference
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]
diff.head()

# Group off-peak prices by companies and month
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()

# Get January and December prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

# Calculate the difference
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]

# Merge the new features into the main dataframe
df = df.merge(diff, on='id', how='left')

#Contract Duration in Days
df['contract_duration'] = (df['date_end'] - df['date_activ']).dt.days

# Time Since Last Product Modification in Days
df['time_since_last_modification'] = (df['date_renewal'] - df['date_modif_prod']).dt.days

# Average Monthly Price Change (using available monthly price data)
monthly_avg_prices = price_df.groupby(['id', price_df['price_date'].dt.to_period('M')]).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()
monthly_avg_prices['price_date'] = monthly_avg_prices['price_date'].dt.to_timestamp()
monthly_avg_prices['monthly_price_change_var'] = monthly_avg_prices.groupby('id')['price_off_peak_var'].diff()
monthly_avg_prices['monthly_price_change_fix'] = monthly_avg_prices.groupby('id')['price_off_peak_fix'].diff()

# Merge average monthly price change into the main dataframe
df = df.merge(monthly_avg_prices[['id', 'price_date', 'monthly_price_change_var', 'monthly_price_change_fix']], left_on=['id', 'date_renewal'], right_on=['id', 'price_date'], how='left').drop(columns=['price_date'])

# Flag for Active Contracts (assuming contracts without end date are active)
df['is_active'] = df['date_end'].isna().astype(int)

# Contract Renewal Rate (number of renewals per year)
renewal_counts = df.groupby(df['date_renewal'].dt.year)['id'].count().reset_index(name='renewals_per_year')
df = df.merge(renewal_counts, left_on=df['date_renewal'].dt.year, right_on='date_renewal')

# Number of Modifications
df['num_modifications'] = df.groupby('id')['date_modif_prod'].transform('count')

print(df.head())

df.to_csv('enhanced_data_with_additional_features.csv', index=False)